# Generated by Django 4.2.8 on 2023-12-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
